#!/usr/bin/env sh
set -e

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$current_branch" =~ ^(master|main|development|rc\/.*)$ ]]; then
  echo "Merge branch tidak di perkenankan pada branch: $current_branch. silahkan menggunakan Pull Request untuk melakukan perubahan."
  exit 1
fi
