#!/usr/bin/env bash
set -e

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$current_branch" =~ ^(master|main|development|rc\/.*)$ ]]; then
  echo "Push ke branch '$current_branch' tidak diperkenankan. Silahkan menggunakan Pull Request untuk melakukan perubahan."
  exit 1
fi
